### ISSUE TITLE
Proje aktif mi

### ISSUE THREAD

**Issue by alicebeci** [YEK-PLUS/maks#1]
Merhaba, bu proje aktif mi? qs modülü bulunamadı hatası aldım.

**Comment by YEK-PLUS** [comment]
Proje aktif, npm log'unu paylaşabilir misiniz?

**Comment by alicebeci** [comment]
> Proje aktif, npm log'unu paylaşabilir misiniz?

[2024-08-22T05_40_12_394Z-debug-0.log](https://github.com/user-attachments/files/16705829/2024-08-22T05_40_12_394Z-debug-0.log)

Tabii ekte sunuyorum hocam. 
Terminalde de şöyle:
PS C:\Users\Administrator\Documents\maks-master> npm install @yek-plus/maks
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/@yek-plus%2fmaks - Not found
npm error 404
npm error 404  '@yek-plus/maks@*' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
npm error A complete log of this run can be found in: C:\Users\Administrator\AppData\Local\npm-cache\_logs\2024-08-22T05_40_12_394Z-debug-0.log
PS C:\Users\Administrator\Documents\maks-master>

**Comment by YEK-PLUS** [comment]
paket npm registry'sinde bulunmadığı için bu hatayı alıyorsunuz. İndirmek için .npmrc dosyasına `@yek-plus` prefixini eklemeniz lazım
`@yek-plus:registry=https://npm.pkg.github.com/`
 veya indirme komutunu şu şekilde düzenleyebilirsiniz.
`npm install https://github.com/YEK-PLUS/maks`
